### ISSUE TITLE
Use CSS Pre-Processor

### ISSUE THREAD

**Issue by gagahpangeran** [cl8n/project-loved-web#17]
Before attempting to do #10 or any more feature that include styling (e.g. add mobile view), there should be some kind of CSS pre-processor.

Advantage:
- Reduce code duplication by using function and mixins.
- Easily use BEM (Block Element Modifier) convention for class naming.

Disadvantage:
- Add more complexity to setup and deploy.
- The styling files would still have many code duplication if not used correctly.

I suggest between two options: SASS or LESS.

Both pre-processor have identical syntax but I tend to use SASS (with SCSS syntax) because I have more experience integrate and setup it with React.

Expected development time : 1-2 days.

---

I'll start working on this once @cl8n agree with this direction.

**Comment by cl8n** [comment]
I've only used LESS but don't mind trying SASS. I went with plain CSS on purpose to keep things simple but somewhere in the create-react-app stack there is CSS processing done anyway...

also not sure how well BEM fits this project, but I won't stop u if u want to try that

i think in general the frameworks used in this project so far are not strong preferences of mine, just whatever allowed me to prototype quickly. same goes for the styles themselves, which had small inspiration from 2000s forums but are otherwise just whatever i came up with on the spot

**Comment by gagahpangeran** [comment]
Got it!

For now just convert the current css into sass.

**Comment by cl8n** [comment]
ended up doing this, and I rewrote a lot of the styles to make use of sass. there are a few odd styles left that have unexpected dependency or `!important` etc, those can be cleaned up whenever they're visited again
