### ISSUE TITLE
Captains & admins should be able to more efficiently moderate "spam" reviews

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved-web#197]
Related to the recent incident with a certain Russian mapper who went out of his way to get him & his friend group to downvote both competitor maps to bring their own up, as well as downvote the maps of people who disagree with.

I'll be honest, I get your idea of leaving the site open to all kinds of reviews & the freedom to let people post their thoughts as you pointed out in the osu! Project Loved Discord server, but at the same time I disagree with the policy on the basis that this stance actively encourages negative behavior, as vote brigading (both positive and negative) essentially goes uncontrolled, which is not how things should be. Encouraging this kind of behavior entirely defeats the point of the website.

Even if it's hard to verify vote brigading at times, stuff like insulting the mapper in the reviews and leaving it in the description of it should not be permissible. Ground rules of "don't be a dick" SHOULD apply to conduct on the website.

My proposal:
Let captains & any admins marked on the site be allowed to delete reviews. There should also be a report button on reviews to report offensive content.

**Comment by cl8n** [comment]
as the site operator I'm not interested in making moderation judgements (basically what I already said on discord)

as someone with project loved's interests in mind I think I just don't agree with this definition of "spam". leaving negative comments toward maps or mappers on loved.sh is a reflection of how some will choose to use the polls on osu.ppy.sh as well, and I don't think any voter should be required to have some deeper or more noble reason for their vote or comment. imo doesn't defeat the point of the website at all, the goal here is no more than to gather some ppl's thoughts on the maps. I would consider something "spam" and worthy of removal if it contributed literally nothing to that end ig, but that's not really the topic here

as the dev I'm mostly interested in keeping things simple.

i dont see myself changing my mind about this one so I'm gonna close. for this particular issue I feel I have a lot more personal responsibility for the outcome, rather than the whole of ppl working on loved, so that's why I'm more okay with thinking "my site my rules" kind of thing.

**Comment by cl8n** [comment]
reconsidering this I'm not really down to delete anything as explained above but I can probs add some way for captains to mark a review as "potentially offensive" or whatever to hide it by default, so each person using the site can choose if they wanna see it

**Comment by cl8n** [comment]
that's probably fair to "hide" if I added this https://github.com/cl8n/project-loved-web/issues/197#issuecomment-1666043038

but in general I'm still just not concerned about this type of comment... to me all they're doing is making a fool of themselves and the nature of limited options to interact on this site means that it can't really be harmful beyond the scope of that review. I also don't think it's accurate to say this is "encouraged", the review system makes starting back-and-forths pretty difficult on purpose and this type of comment is an extreme minority. keeping reviews interesting& productive is important but I just don't see an issue here that warrants the dev time and additional oversight
