### ISSUE TITLE
Website does not allow selecting other modes as excluded diffs

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved-web#25]
If a multi-mode set is nominated for a Loved wave, you cannot select the other modes as "excluded". This causes confusion among voters as the news post generates without mentioning that other modes are not being nominated. Example images below:

Multi-mode set:
![](https://i.imgur.com/IKjAy4m.png)

When nominated for osu!standard, you cannot choose the osu!mania difficulties as excluded diffs (only osu!standard diffs):
![](https://i.imgur.com/89bXYt8.png)

For the sake of clarity when news posts are made, we should be allowed to choose other modes as excluded if needed to avoid confusion like [oo oo's Blue Zenith](https://osu.ppy.sh/beatmapsets/89139) as it wasn't mentioned that the osu!standard difficulty wasn't being nominated (we couldn't select it as such).

**Comment by cl8n** [comment]
as said on discord other modes are "excluded" by default, you have to include them on purpose by adding an attached poll with parent ID

for now I don't think we should change the news post / forum threads either cuz there's no reason for people to be looking for maps of other modes in the section clearly labeled as another. looking at those beatmap comments, the issue definitely seems to be coming from the loved beatmap listing, rather than anything related to this website or news post

**Comment by cl8n** [comment]
same map used in the osu-web report https://github.com/ppy/osu-web/issues/7832
