### ISSUE TITLE
Add mapper consents edit view

### ISSUE THREAD

**Issue by cl8n** [cl8n/project-loved-web#29]
continued from #5 , should talk to huu about this one to see what would work

**Comment by huuishuu** [comment]
The way I see it is that the "Mapper consents" page should have a + to allow us to add new entries and an edit button next to each entry on the page.

Both the new entry & the edit panel should have the following information:

User ID (username gets automatically filled in grabbing the user's current username on the osu! website)
Permission status (Yes, No, No reply, Unreachable)
A place to put in beatmap IDs (for exclusions/whitelisting)
A place to put down notes

Here's a proof-of-concept MS Paint sketch (I'm putting my project management studies to good use clearly 💀)
![](https://i.imgur.com/7u1QrkK.png)

How feasible would it be to have someplace to display the mapper's previous names, if applicable? Using someone like Delis, for example, who was known as ShirohaMyMommy for a few maps. Though admittedly the use-case for something like this wouldn't be massively widespread unless the mapper themselves is inactive.

**Comment by tybug** [comment]
the api does give us `previous_usernames` so that should be doable, though [Delis](https://osu.ppy.sh/users/1603923) in particular doesn't have `ShirohaMyMommy` listed as a previous username for some reason (am I remembering right that osu doesn't show username reverts in history? that might be why)

**Comment by huuishuu** [comment]
> 
> 
> the api does give us `previous_usernames` so that should be doable, though [Delis](https://osu.ppy.sh/users/1603923) in particular doesn't have `ShirohaMyMommy` listed as a previous username for some reason (am I remembering right that osu doesn't show username reverts in history? that might be why)

It is true, yeah. If a name has been reverted - it does not get added to the "Previously known as" thing on the osu! website so I reckon APIs won't pick them up either. Perhaps allowing to manually add these types of usernames in would be a good compromise?

**Comment by huuishuu** [comment]
One idea I have for the mapper consents page is to let the user themselves specify their own permissions to have their maps in Loved or not, avoiding the need to have us mass-message them ourselves.

In other words, user logs in -> can set their own permissions to "Yes" or "No", while specifying which maps they want to blacklist/whitelist.

Would give more purpose to log into the website other than just to submit a map, no?

**Comment by cl8n** [comment]
can do that but it's no substitute for proactively asking for consent, especially becaused loved assumes silence means yes. you also shouldn't use it within the mass message (e.g. "please fill out thing on \<website\>") because it shouldn't require logging into a third party service just to say you don't want your work to be involved with that service. if added, that'll only be for the convenience of people who would visit the site already

short of building something meaningful into first-party system I don't think there's any getting around that you need to proactively message everybody, so I'm looking for ways to make it less annoying to maintain

**Comment by huuishuu** [comment]
Well, regarding messaging everybody - it's currently just uh...well, incredibly inconvenient given how broken forum PMs are (most people either don't read or don't know how to access them, I've had some report to me in the past that they've received a message but couldn't open it because old website is just too broken for them).

Still, a convenience feature like that would be nice for those visiting loved.sh so I think it should definitely be considered. Granted, yeah - I agree that users shouldn't be *required* to log into the site to fill it out, but the option should be there for them to do it themselves if they don't receive a message. Especially in the current climate of old website PMs being broken beyond repair at this point.

**Comment by huuishuu** [comment]
Any idea when this is going to be possible? There are a select few mappers who really want to change their consent status (such as Shoegazer) but at the moment all I can do is tell them "sorry I can't change that yet".

**Comment by cl8n** [comment]
no, until i start doing news post and stuff again dont count on me to have any predictable time spent on this project

**Comment by cl8n** [comment]
added
