### ISSUE TITLE
Separate Entries in the "Submissions" Page

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved-web#35]
With the way the current [Submissions](https://loved.sh/submissions/osu) page looks, it's an eye-sore and a huge mess. With nothing separating each entry, it just looks like a huge wall of text where you're not sure where it starts and where it ends.

I propose to separate the submissions on the pages themselves to make it more clear & concise, as well as make it more obvious where it starts & ends.

This could be done in 2 ways:
- separate each entry by row & column
- separate each entry by just the row

I've made 2 concept mock-ups in MS Paint.

Version A with column & row separate:

![](https://i.imgur.com/Hod3Ycu.png)

Version B with just the row separate:

![](https://i.imgur.com/AYiyW1v.png)

Alongside this, each entry should be more spaced out between them to avoid making them look too cluttered, as that's the main criticism I've seen a few captains bring up regarding the way it looks currently.

**Comment by kadoen** [comment]
I think version A would be best for the current total horizontal spacing, especially if there's a lot of maps - maybe also centering some of the numbers. Option B would work, but I think it needs more whitespace between some of the columns (e.g. Plays/Favs/Year)

**Comment by cl8n** [comment]
per-row I think the view is already fine but I'll experiment with more left and right border spacing
the lines between rows in both of these images seems like a good temporary solution but I'm not sure I want to keep this so obviously a table forever. I only started with a table since I was looking at the old sheet, but I never came up with something better for each mapset 😢

and the dropdowns are still crap, I have a feeling those will never fit well within a table...

**Comment by huuishuu** [comment]
POCARI SWEAT made this much-nicer looking mock-up which is an idea of how it could look like.

![](https://i.imgur.com/u2QEB66.png)

**Comment by cl8n** [comment]
- no side margin for table (on accident because I had to reformat this whole table using collapsed borders, but I think it looks alright and gives more horizontal space so w/e)
- slightly larger top and bottom margins for each row and table header
- border between rows
- icons for the columns shown above
- no line between reviews and submissions in the dropdown
- changed "add review"/"update review" to just "review", for space

**Comment by cl8n** [comment]
years and diff counts span two lines now for their two components each, saves more space 💸

**Comment by cl8n** [comment]
gonna close this since the entries are now more "separate" as requested, open new issue or say in #osu-loved if there's more to change abt this page
